apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formular-showcase
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: showcase.formular.codernic.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: formular-showcase
                port:
                  number: 80
